openapi: 3.0.3
info:
  title: ''

servers:
  - url: https://api.paysecure.net    

paths:
  /api/v1/purchases:
    post:
      tags: [INTERAC-ETRANSFER]
      summary: Initiate a new purchase via INTERAC-ETRANSFER
      parameters:
        - in: header
          name: Authorization
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - client
                - purchase
                - paymentMethod
                - merchantRef
                - brand_id
                - success_redirect
                - failure_redirect
                - success_callback
                - failure_callback
              properties:
                client:
                  type: object
                  required: [email, full_name, country, city, stateCode, street_address, zip_code, phone, tax_number]
                  properties:
                    email: { type: string, format: email, example: client@email.com }
                    full_name: { type: string, example: Client Name }
                    country: { type: string, example: CA }
                    city: { type: string, example: Toronto }
                    stateCode: { type: string, example: ON }
                    street_address: { type: string, example: 123 5th Ave, Toronto }
                    zip_code: { type: string, example: 10010 }
                    phone: { type: string, example: 9999999999 }
                    tax_number: { type: string, example: 39933551809 }
                purchase:
                  type: object
                  required: [currency, products]
                  properties:
                    currency: { type: string, example: CAD }
                    products:
                      type: array
                      items:
                        type: object
                        required: [name, price]
                        properties:
                          name: { type: string, example: Product Name }
                          price: { type: number, example: 10 }
                paymentMethod: { type: string, example: INTERAC-ETRANSFER }
                merchantRef: { type: string, example: efsdjhvbr34r3 }
                brand_id: { type: string, format: uuid, example: 30f7ce6e-3b7e-46a2-9b50-484fc55be689 }
                success_redirect: { type: string, format: uri, example: https://your.success.redirect.com }
                failure_redirect: { type: string, format: uri, example: https://your.failure.redirect.com }
                pending_redirect: { type: string, format: uri, example: https://your.pending.redirect.com }
                success_callback: { type: string, format: uri, example: https://your.success.callback.com }
                failure_callback: { type: string, format: uri, example: https://your.failure.callback.com }
                expiryinmin: { type: string, example: "30" }
      responses:
        '200':
          description: Purchase Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  purchaseId: { type: string, example: 689c53b297281b45aac80cc2 }
                  client:
                    type: object
                    properties:
                      email: { type: string, example: client@email.com }
                      full_name: { type: string, example: Client Name }
                      country: { type: string, example: CA }
                      city: { type: string, example: Toronto }
                      stateCode: { type: string, example: ON }
                      street_address: { type: string, example: 123 5th Ave, Toronto }
                      zip_code: { type: string, example: 10010 }
                      phone: { type: string, example: 9999999999 }
                      tax_number: { type: string, example: 39933551809 }
                  updated_on: { type: integer, example: 1755075511 }
                  type: { type: string, example: purchase }
                  paymentMethod: { type: string, example: INTERAC-ETRANSFER }
                  amountUnit: { type: string, example: MAJOR }
                  errorMsg: { type: string, example: "" }
                  redirectType: { type: string, example: POST }
                  force_recurring: { type: boolean, example: false }
                  created_on: { type: integer, example: 1755075506 }
                  merchantRef: { type: string, example: efsdjhvbr34r3 }
                  merchantName: { type: string, example: arunsinghal }
                  purchase:
                    type: object
                    properties:
                      currency: { type: string, example: CAD }
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            name: { type: string, example: Product Name }
                            quantity: { type: integer, example: 1 }
                            price: { type: number, example: 10 }
                      total: { type: number, example: 10 }
                      language: { type: string, example: en }
                      total_formatted: { type: number, example: 1 }
                      expireInMin: { type: string, example: "43200" }
                  payment:
                    type: object
                    properties:
                      amount: { type: number, example: 10 }
                      currency: { type: string, example: CAD }
                      net_amount: { type: number, example: 10 }
                      paid_on: { type: integer, example: 1755075506 }
                  issuer_details:
                    type: object
                    properties:
                      legal_name: { type: string, example: test6 }
                      brand_name: { type: string, example: test6 }
                  transaction_data:
                    type: object
                    properties:
                      flow: { type: string, example: payform }
                      extra:
                        type: object
                        properties:
                          amount: { type: number, example: 10 }
                          masked_pan: { type: string, example: INTERAC-ETRANSFER }
                  status: { type: string, example: PAYMENT_IN_PROCESS }
                  status_history:
                    type: array
                    items:
                      type: object
                      properties:
                        status: { type: string, example: payment_in_process }
                        timestamp: { type: integer, example: 1755075511 }
                  is_test: { type: boolean, example: false }
                  brand_id: { type: string, example: 30f7ce6e-3b7e-46a2-9b50-484fc55be689 }
                  reference_generated: { type: string, example: PS1172 }
                  issued: { type: string, example: 2025-08-13 }
                  checkout_url: { type: string, example: https://api.choicepay.ca/payments/689c53b297281b45aac80cc2/ }
                  payInDetails:
                    type: object
                    properties:
                      name: { type: string, example: INTERAC E-TRANSFER }
                      emailAddress: { type: string, example: mtbx@paylitnow.com }
                      secretQA: { type: string, example: q1172202 }
                      secretAnswer: { type: string, example: a1172202 }
        '401':
          description: Authorization Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string, example: Invalid Authorization }
                  code: { type: string, example: Invalid_Authorization }
