openapi: 3.0.3
info:
  title: ''

servers:
  - url: https://api.paysecure.net    
  
paths:
  /api/v1/payment_methods:
    post:
      tags: [Payment Methods]
      summary: Get available payment methods
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              example: {}
      responses:
        '200':
          description: List of payment methods
          content:
            application/json:
              schema:
                type: object
                properties:
                  available_payment_methods:
                    type: array
                    items:
                      type: string
                    example:
                      - QBPAYFTOPUP
                      - visa
                      - PIX
                      - INTERAC
                      - FawryPay
                      - INTERAC-E-TRANSFER
                      - amex
                      - MASTER
                      - jcb
                      - UzCard
                      - humo
                      - INTERAC-ETRANSFER
                      - INTERAC-REQUEST-MONEY
                      - THIRDPARTY-NETBANKING
                      - BANKTRANSFER
                      - discover
                      - EASEBUZZ
                      - eNaira
                      - KLARNA
                      - KoraPayMobileMoney
                      - MOBILEMONEY
                      - SPEI
                      - QBPAY
                      - UPI
                      - CASHFREE
                      - THIRDPARTY-UPI
                      - PAYID
                      - NEOSURF
                      - CRYPTO-BRIDGE
                      - INTERAC-EXPRESS
                  by_country:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                  country_names:
                    type: object
                    additionalProperties:
                      type: string
                  names:
                    type: object
                    additionalProperties:
                      type: string
                  card_methods:
                    type: array
                    items:
                      type: string
